export interface ISkuIntXML {
	"NETLOGMESSAGE": {
	  "MESSAGEID": String,
	  "MESSAGETYPE": String,
	  "SOURCEID": String,
	  "SENTTIMESTAMP": String,
	  "CLIENTID": String,
	  "CLIENTSESSION": Number,
	  "MESSAGE": {
			"HEADER": {
				"DATA": {
					"CONSIGNEE": String,
					"SKU": String,
					"SKUDESC": String,
					"SKUSHORTDESC": String,
					"MANUFACTURERSKU": String,
					"VENDORSKU": String,
					"OTHERSKU": String,
					"SKUGROUP": String,
					"CLASSNAME": String,
					"STATUS": Boolean,
					"INVENTORY": Boolean,
					"NEWSKU": Boolean,
					"INITIALSTATUS": String,
					"VELOCITY": String,
					"ONSITEMIN": String,
					"ONSITEMAX": String,
					"LASTCYCLECOUNT": String,
					"CYCLECOUNTINT": String,
					"LOWLIMITCOUNT": String,
					"PREFLOCATION": String,
					"PREFPUTREGION": String,
					"UNITPRICE": String,
					"PICTURE": String,
					"PICKSORTORDER": String,
					"DEFAULTUOM": String,
					"EDITDATE": String,
					"EDITUSER": String,
					"OVERPICKPCT": String,
					"OVERRECEIVEPCT": String,
					"JOBTYPE": String,
					"RoHoSCOMPATIABLE": String,
					"HSC": String,
					"COUNTRYOFORIGIN": String,
					"WEIGHT": String,
					"HEIGHT": String,
					"DEPTH": String,
					"WIDTH": String,
					"VOLUME": String,
					"FLAMMABLE": String,
					"SHELFLIFE": String,
					"ATTRIBUTE2": String,
					"ATTRIBUTE3": String,
					"ATTRIBUTE4": String,
					"CURRENCY": String,
					"EXPORTED": String,
					"DATALEVEL2": {
					"DATA2":
						{
						"CONSIGNEE": String,
						"SKU": String,
						"UOM": String,
						"EANUPC": String,
						"GROSSWEIGHT": String,
						"NETWEIGHT": String,
						"LENGTH": String,
						"WIDTH": String,
						"HEIGHT": String,
						"VOLUME": String,
						"LOWERUOM": String,
						"UNITSPERMEASURE": Number,
						"UNITSPERLOWESTUOM": Number,
						"SHIPPABLE": String,
						"EDITDATE": String,
						"EDITUSER": String
						}[]
					}
				}
			}
	  }
	}
}

export interface ISkuInt {
	"messagetype": String,
	"messageid": String,
	"sourceid": String,
	"senttimestamp": String,
	"clientid": String,
	"clientsession": Number,
	"consignee": String,
	"sku": String,
	"skudesc": String,
	"skushortdesc": String,
	"manufacturersku": String,
	"vendorsku": String,
	"othersku": String,
	"skugroup": String,
	"classname": String,
	"status": Boolean,
	"inventory": Boolean,
	"newsku": Boolean,
	"initialstatus": String,
	"velocity": String,
	"onsitemin": String,
	"onsitemax": String,
	"lastcyclecount": String,
	"cyclecountint": String,
	"lowlimitcount": String,
	"preflocation": String,
	"prefputregion": String,
	"unitprice": String,
	"picture": String,
	"picksortorder": String,
	"defaultuom": String,
	"editdate": String,
	"edituser": String,
	"overpickpct": String,
	"overreceivepct": String,
	"jobtype": String,
	"rohoscompatiable": String,
	"hsc": String,
	"countryoforigin": String,
	"weight": String,
	"height": String,
	"depth": String,
	"width": String,
	"volume": String,
	"flammable": String,
	"shelflife": String,
	"attribute2": String,
	"attribute3": String,
	"attribute4": String,
	"currency": String,
	"exported": String,
	"datalevel2": any
}